name: Update README Activity

on:
  schedule:
    - cron: '*/30 * * * *' # runs every 30 minutes
  workflow_dispatch: # allows manual run from GitHub Actions tab

jobs:
  update-readme:
    name: Update Profile Activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Currently Building
        run: node scripts/update-currently-building.js

      - name: Commit Currently Building
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "⚡ Update currently building in README"
          git push

      - name: Update GitHub Activity
        uses: gautamkrishnar/github-activity-readme@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update recent activity in biography README"
          MAX_LIMIT: 5
